#!/bin/sh

if [ ! -f $1 ]
then
    echo -e "file doesn't exists\n"
    exit 1
fi

cat $1 | tr -d '\r' > .$1.bak
if [ $? == '0' ];then
    rm -r $1
    mv .$1.bak $1
else
    echo "tr failed"
fi

exit 0


